<a href="https://colab.research.google.com/github/jabarragann/PytorchTutorialsJuanAntonio/blob/master/TensorFlowTutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing libraries



In [0]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

#Building and running the computational Graph



##Simple example

In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)


Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


##Sesion


In [6]:
sess = tf.Session()
print(sess.run(total))
print(sess.run({'ab':(a, b), 'total':total}))

7.0
{'ab': (3.0, 4.0), 'total': 7.0}


In [7]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.33743107 0.8831227  0.52798796]
[0.38428628 0.8174068  0.7911519 ]
(array([1.0054328, 1.3116302, 1.285294 ], dtype=float32), array([2.0054328, 2.3116302, 2.285294 ], dtype=float32))


##Feeding the graph with data



In [9]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))



7.5
[3. 7.]


##Creating Layers



In [11]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y, {x: [[1, 2, 3],[4, 5, 6]]}))

[[-3.793593]
 [-7.500197]]


#Coursera Example


In [23]:
import numpy as np 
import tensorflow as tf 

coefficients = np.array([[1.],[-10],[25]])
w = tf.Variable(0,dtype=tf.float32)
x = tf.placeholder(tf.float32, [3,1])

#cost =  w ** 2 -10 * w + 25
cost = x[0,0]*w**2+x[1,0]*w+x[2,0]

train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

init = tf.global_variables_initializer()
session = tf.Session()
session.run(init)

print(session.run(w))

#Train model
for i in range(1000):
    session.run(train, feed_dict={x:coefficients})
    
print(session.run(w))


0.0
4.999988
